### ISSUE TITLE
Unexpected $type value: `app.bsky.embed.external#main`

### ISSUE THREAD

**Issue by mozzius** [andooown/swift-atproto#25]
I think this might be my fault - Graysky will sometimes create posts that contains an embed record with a `$type` of `app.bsky.embed.external#main`. This is valid according to the ATProto spec, however, it fails to be parsed since I think this library is expecting it to just be `app.bsky.embed.external`. Ran into this trying to use `getFeed`

It'd be great if it allowed both variations!

**Comment by andooown** [comment]
Thanks for your report!

> `$type` of `app.bsky.embed.external#main`. This is valid according to the ATProto spec, however, it fails to be parsed since I think this library is expecting it to just be `app.bsky.embed.external`. 

Yes, it seems a bug of this library. OK, I'll try to fix it later.

**Comment by andooown** [comment]
@mozzius 
I fixed it by #27 and confirmed decoding with `$type = <NSID>#main` by [tests](https://github.com/andooown/swift-atproto/pull/27/files#diff-584b4d9d8ff3cae78990360ce67f5e6ccd530cad24cd638767f0cf9cbfd84d61R38) ✅ 

Thanks for your report 🙇
